### ISSUE TITLE
Upgrade RPC Supported Chain

### ISSUE THREAD

**Issue by ducmanh1101** [Desig-Labs/supported-chains#40]

**Comment by ducmanh1101** [comment]
Supported by ankr: 
- Aptos ( Main, test)
- Arbitrum (Mainnet)
- Avax (Main, test)
- Base (Main, test)
- Bsc (Main, test)
- Ether (Main, goerli, sepolia)
- Moonbeam 
- Polygon (Main, test)
- Polygon-zkevm (main, test)
- Sei (main, test)
- zeta (test)
- Linea (Main)
- Sui ( Main, test)
- Solana (main, dev)

Unsupported by ankr
- Aptos (dev -  https://fullnode.devnet.aptoslabs.com/ )
- Arbitrum (Test -https://goerli-rollup.arbitrum.io/rpc)
- Moombase https://rpc.api.moonbase.moonbeam.network/
- Movement - https://seed-node1.movementlabs.xyz/
- Shardeum (test - https://dapps.shardeum.org/)
- Sui (dev - https://fullnode.devnet.sui.io/
- Linea (Test - https://linea-goerli.infura.io/v3/93597110afce4130a8f962c0abf2f73c)
- Viction (Main - https://rpc.tomochain.com/, Test - https://rpc.testnet.tomochain.com/)
- Zeta (main - https://api.mainnet.zetachain.com/evm)
- Solana ( test https://api.testnet.solana.com/)
- Taiko https://rpc.jolnir.taiko.xyz/

**Comment by ducmanh1101** [comment]
Unsupported by ankr
- Aptos (dev -  https://fullnode.devnet.aptoslabs.com/ )
- Arbitrum (Test -https://goerli-rollup.arbitrum.io/rpc)
- Moombase https://rpc.api.moonbase.moonbeam.network/
- Movement - https://seed-node1.movementlabs.xyz/
- Shardeum (test - https://dapps.shardeum.org/)
- Sui (dev - https://fullnode.devnet.sui.io/
- Linea (Test - https://linea-goerli.infura.io/v3/93597110afce4130a8f962c0abf2f73c)
- Viction (Main - https://rpc.tomochain.com/, Test - https://rpc.testnet.tomochain.com/)
- Zeta (main - https://api.mainnet.zetachain.com/evm)
- Solana ( test https://api.testnet.solana.com/)
- Taiko https://rpc.jolnir.taiko.xyz/

**Comment by dmcong** [comment]
LGTM!
